apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-healthz
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: test-healthz
    spec:
      containers:
      - name: test-healthz
        image: artaxmax/test-healthz:latest
        command: ["/bin/sh"]
        args:
        - "-c"
        - "node app.js"
        env:
        - name: param1
          value: "8"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: test-healthz
spec:
  selector:
    app: test-healthz
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer