apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-healthz
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-healthz
    spec:
      containers:
      - name: test-healthz
        image: artaxmax/test-healthz:latest
        command: ["/bin/sh"]
        args:
        - "-c"
        - "node app.js"
---
apiVersion: v1
kind: Service
metadata:
  name: test-healthz
spec:
  selector:
    app: test-healthz
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer